### PR TITLE
[Improve][Build] Use pulsar client as a submodule for C++ projects

### LINKED ISSUE #100: [Build] Can't use it as a submodule
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

Ubuntu 22.04, cmake 3.22, Pulsar Repo: master

### Minimal reproduce step

files structure:
project_dir
  -> source/main.cpp
  -> thirdparty/pulsar-client (<- this is submodule 'git submodule add https://github.com/apache/pulsar-client-cpp.git thirdparty/pulsar-client')
  -> CMakeLists.txt

CMakeLists.txt:
`cmake_minimum_required(VERSION 3.14)

project(
    ppp
    VERSION 0.1.0
    DESCRIPTION "Short description"
    HOMEPAGE_URL "https://example.com/"
    LANGUAGES CXX
)

set(BUILD_STATIC_LIB ON CACHE BOOL "" FORCE)
set(BUILD_DYNAMIC_LIB OFF CACHE BOOL "" FORCE)
set(BUILD_TESTS OFF CACHE BOOL "" FORCE)
add_subdirectory(thirdparty/pulsar-client)

add_executable(ppp_exe source/main.cpp)
set_property(TARGET ppp_exe PROPERTY OUTPUT_NAME ppp)
target_compile_features(ppp_exe PRIVATE cxx_std_17)

target_link_libraries(ppp_exe PRIVATE pulsarStatic)
`

### What did you expect to see?

Compiles and links without error

### What did you see instead?

Minimal example does not compiles - errors like 

> In file included from <cut>/p/thirdparty/pulsar-client/lib/Backoff.cc:19:
<cut>/p/thirdparty/pulsar-client/lib/Backoff.h:21:10: fatal error: pulsar/defines.h: No such file or directory
   21 | #include <pulsar/defines.h>

and so on - all include paths for pulsar client are wrong. 

Verbose output:
usr/bin/c++ -DBOOST_ALLOW_DEPRECATED_HEADERS -DBOOST_ALL_NO_LIB -DBUILDING_PULSAR -DHAS_SNAPPY=0 -DHAS_ZSTD=0 -DLOG_CATEGORY_NAME=\"pulsar.\" -I<cut>/p -I<cut>/p/include -I<cut>/_build/p/include -I<cut>/_build/p/generated -I<cut>/_build/p/generated/lib -g -fPIC -Wall -Wformat-security -Wvla -Werror -Wno-sign-compare -Wno-deprecated-declarations -Wno-error=cpp -msse4.2 -mpclmul -Wno-stringop-truncation -fdiagnostics-show-option -fdiagnostics-color -fvisibility=hidden -Wl,--exclude-libs,ALL -std=gnu++11 -MD -MT thirdparty/pulsar-client/lib/CMakeFiles/PULSAR_OBJECT_LIB.dir/Backoff.cc.o -MF thirdparty/pulsar-client/lib/CMakeFiles/PULSAR_OBJECT_LIB.dir/Backoff.cc.o.d -o thirdparty/pulsar-client/lib/CMakeFiles/PULSAR_OBJECT_LIB.dir/Backoff.cc.o -c <cut>/p/thirdparty/pulsar-client/lib/Backoff.cc

### Anything else?

I looked at main CMakeLists.txt in pulsar-client-cpp and there is error, I guess - you have to use PROJECT_<SOURCE/BINARY>_DIR instead of CMAKE_<>_DIR, in that case everything compiles and links.

Also cmake for tests using CMAKE_SOURCE_DIR to address some include dirs

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by fregate**
Fixes #100 

### Motivation

If your project builds through CMake and you try to add pulsar-client in some directory for build with whole project (i.e. third-party submodule) you can't do this because pulsar-client CMake uses CMAKE_*_DIR for configure, and this variable always related to top-level project.

### Modifications

Change CMAKE_(SOURCES|BINARY)_DIR to PROJECT_*_DIR for library and tests

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
Build process already covered in documentation

- [ ] `doc` 
(Your PR contains doc changes)

- [x] `doc-complete`
Build process already covered in documentation

### CODE REVIEW

**Comment by fregate** [comment]
change base branch

**Review by BewareMyPower — CHANGES_REQUESTED** [review]
Could you change the target branch from `branch-3.0` to `master` so that CI will be run?

**Comment by merlimat** [comment]
It probably needs to be rebased on top of `main` branch. The github switch branch is messing things up.

**Comment by fregate** [comment]
I can't build `main` branch (tests)

```
FAILED: tests/CMakeFiles/pulsar-tests.dir/KeyValueSchemaTest.cc.o 
ccache /usr/bin/c++ -DBOOST_ALLOW_DEPRECATED_HEADERS -DBOOST_ALL_NO_LIB -DBUILDING_PULSAR -DHAS_SNAPPY=0 -DHAS_ZSTD=0 -DLOG_CATEGORY_NAME=\"pulsar.\" -I/.../ws/check/pulsar/patch -I/.../ws/check/pulsar/patch/include -I/.../ws/check/pulsar/_build/patch/include -I/.../ws/check/pulsar/_build/patch/generated -I/.../ws/check/pulsar/_build/patch/generated/tests -I/.../ws/check/pulsar/patch/lib -I/.../ws/check/pulsar/_build/patch/generated/lib -g -fPIE -Wall -Wformat-security -Wvla -Werror -Wno-sign-compare -Wno-deprecated-declarations -Wno-error=cpp -msse4.2 -mpclmul -Wno-stringop-truncation -fdiagnostics-show-option -fdiagnostics-color -fvisibility=hidden -Wl,--exclude-libs,ALL -std=gnu++11 -MD -MT tests/CMakeFiles/pulsar-tests.dir/KeyValueSchemaTest.cc.o -MF tests/CMakeFiles/pulsar-tests.dir/KeyValueSchemaTest.cc.o.d -o tests/CMakeFiles/pulsar-tests.dir/KeyValueSchemaTest.cc.o -c /.../ws/check/pulsar/patch/tests/KeyValueSchemaTest.cc
In file included from /usr/include/gtest/gtest-matchers.h:44,
                 from /usr/include/gtest/internal/gtest-death-test-internal.h:39,
                 from /usr/include/gtest/gtest-death-test.h:41,
                 from /usr/include/gtest/gtest.h:64,
                 from /.../ws/check/pulsar/patch/tests/KeyValueSchemaTest.cc:19:
/usr/include/gtest/gtest-printers.h: In instantiation of ‘struct testing::internal::FindFirstPrinter<pulsar::KeyValueEncodingType, void, testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter, testing::internal::ProtobufPrinter, testing::internal::ConvertibleToIntegerPrinter, testing::internal::ConvertibleToStringViewPrinter, testing::internal::RawBytesPrinter, testing::internal::FallbackPrinter>’:
/usr/include/gtest/gtest-printers.h:287:8:   recursively required from ‘struct testing::internal::FindFirstPrinter<pulsar::KeyValueEncodingType, void, testing::internal::FunctionPointerPrinter, testing::internal::PointerPrinter, testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter, testing::internal::ProtobufPrinter, testing::internal::ConvertibleToIntegerPrinter, testing::internal::ConvertibleToStringViewPrinter, testing::internal::RawBytesPrinter, testing::internal::FallbackPrinter>’
/usr/include/gtest/gtest-printers.h:287:8:   required from ‘struct testing::internal::FindFirstPrinter<pulsar::KeyValueEncodingType, void, testing::internal::ContainerPrinter, testing::internal::FunctionPointerPrinter, testing::internal::PointerPrinter, testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter, testing::internal::ProtobufPrinter, testing::internal::ConvertibleToIntegerPrinter, testing::internal::ConvertibleToStringViewPrinter, testing::internal::RawBytesPrinter, testing::internal::FallbackPrinter>’
/usr/include/gtest/gtest-printers.h:307:9:   required from ‘void testing::internal::PrintWithFallback(const T&, std::ostream*) [with T = pulsar::KeyValueEncodingType; std::ostream = std::basic_ostream<char>]’
/usr/include/gtest/gtest-printers.h:441:30:   required from ‘void testing::internal::PrintTo(const T&, std::ostream*) [with T = pulsar::KeyValueEncodingType; std::ostream = std::basic_ostream<char>]’
/usr/include/gtest/gtest-printers.h:691:12:   required from ‘static void testing::internal::UniversalPrinter<T>::Print(const T&, std::ostream*) [with T = pulsar::KeyValueEncodingType; std::ostream = std::basic_ostream<char>]’
/usr/include/gtest/gtest-printers.h:980:30:   required from ‘void testing::internal::UniversalPrint(const T&, std::ostream*) [with T = pulsar::KeyValueEncodingType; std::ostream = std::basic_ostream<char>]’
/usr/include/gtest/gtest-printers.h:865:19:   required from ‘static void testing::internal::UniversalTersePrinter<T>::Print(const T&, std::ostream*) [with T = pulsar::KeyValueEncodingType; std::ostream = std::basic_ostream<char>]’
/usr/include/gtest/gtest-printers.h:1018:44:   required from ‘std::string testing::PrintToString(const T&) [with T = pulsar::KeyValueEncodingType; std::string = std::__cxx11::basic_string<char>]’
/usr/include/gtest/internal/gtest-param-util.h:593:28:   required from ‘void testing::internal::ParameterizedTestSuiteInfo<TestSuite>::RegisterTests() [with TestSuite = KeyValueSchemaTest]’
/usr/include/gtest/internal/gtest-param-util.h:543:8:   required from here
/usr/include/gtest/gtest-printers.h:291:36: error: no matching function for call to ‘testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter::PrintValue(const pulsar::KeyValueEncodingType&, std::nullptr_t)’
  291 |     T, decltype(Printer::PrintValue(std::declval<const T&>(), nullptr)),
      |                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/gtest/gtest-printers.h:212:15: note: candidate: ‘template<class T, class, class> static void testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter::PrintValue(const T&, std::ostream*)’
  212 |   static void PrintValue(const T& value, ::std::ostream* os) {
      |               ^~~~~~~~~~
/usr/include/gtest/gtest-printers.h:212:15: note:   template argument deduction/substitution failed:
/usr/include/gtest/gtest-printers.h:211:33: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘const pulsar::KeyValueEncodingType’)
  210 |             typename = decltype(std::declval<std::ostream&>()
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  211 |                                 << std::declval<const T&>())>
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Release tag build correctly

configure command: `cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache`
build command: `cmake --build --target pulsar-tests -j 15`

CMake output:
```
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0

-- LINK_STATIC:  OFF
-- Using CCache
-- ARCHITECTURE: x86_64
-- BUILD_DYNAMIC_LIB:  ON
-- BUILD_STATIC_LIB:  ON
-- BUILD_TESTS:  ON
-- BUILD_WIRESHARK:  OFF
-- BUILD_PERF_TOOLS:  OFF
-- USE_LOG4CXX:  OFF
-- CMAKE_BUILD_TYPE:  Debug
```

**Comment by fregate** [comment]
It looks like that 
[feat] Support KeyValue Schema. #22 (https://github.com/apache/pulsar-client-cpp/pull/22)
PR broke it, because if I remove KeyValueSchemaTest.cc from tests - It works

Does CI build tests? If not - I can rebase
But it looks weird - no tests in CI )

**Comment by fregate** [comment]
Rebased
(tests not compiles)

**Review by BewareMyPower — APPROVED** [review]

**Pull request merged**
