### PR TITLE
Enable required check status for PR validation

### PR DESCRIPTION
**Pull request by RobertIndie**
### Motivation

Currently,  there is no required workflow for the PR.

### Modifications

Enable required check status for pr validation

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by merlimat — APPROVED** [review]

**Comment by BewareMyPower** [comment]
Could you take a look at the **Build Alpine Linux APK Package** task? It stuck at Waiting for status to be reported

image

**Comment by BewareMyPower** [comment]
image

In addition, these two tasks (especially the most important unit tests task) are not required.

**Comment by RobertIndie** [comment]
> image
> 
> In addition, these two tasks (especially the most important unit tests task) are not required.

The unit test is dependent by other jobs. 
image

**Comment by BewareMyPower** [comment]
> I found that there is no CentOS7 matrix in the CI job:

Because it was removed in #25.

**Pull request merged**
