### PR TITLE
Add windows release artifacts

### PR DESCRIPTION
**Pull request by yaalsn**
### Motivation

Add windows release artifacts and create a release with artifacts after pushing tag.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by BewareMyPower — APPROVED** [review]

**Comment by merlimat** [comment]
@yaalsn @BewareMyPower This has changed from uploading the binaries to GH actions artifacts into a release. It is breaking the release workflow. 
First, we still must upload as artifacts, but also we may not have the credentials to upload to GH releases.

**Comment by yaalsn** [comment]
@merlimat The uploaded artifacts are release artifacts which need by users, and they don't need to build by themself. The token is GITHUB_TOKEN which is a builtin token in GitHub action so that we can use it directly. 

About GITHUB_TOKEN:

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

**Comment by shibd** [comment]
> @merlimat The uploaded artifacts are release artifacts needed by users, and they don't need to build themself. The token is GITHUB_TOKEN which is a builtin token in GitHub action so that we can use it directly.
> 
> About GITHUB_TOKEN:
> 
> https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

I think we need to keep uploading the binaries to GH action artifacts. This is required for the current release process. You can refer to the following:

- https://github.com/apache/pulsar-client-cpp/wiki/Committer-Release-Guide#sign-and-stage-the-artifacts
- https://github.com/apache/pulsar-client-cpp/blob/main/build-support/stage-release.sh

**Comment by yaalsn** [comment]
Thanks @shibd, I didn't notice the release guide before.

**Comment by merlimat** [comment]
@yaalsn we could keep the upload to GH release as an optional step, enabled only if some flag is set. For Apache releases, we need to anyway follow the process of staging the binaries.

**Pull request merged**
